# Personal overrides for the SakuraTheme theme.
prefixName: ''
siteName: Execapes
url: https://execapes.github.io
description: Welcome to Execapes' personal blog.
avatar: https://github.com/execapes.png
